export const rolesConfig = [
  { id: 0, label: "User" },
  { id: 1, label: "Manager" },
  { id: 2, label: "Boss" },
];

export const sectionsConfig = [
  {
    id: "home",
    label: "Home",
    path: "/home",
    iconRegular: "home.png",
    iconActive: "home.fill.png",
    showInNav: true,
    showInMenu: true,
    showInPermissions: true,
    alwaysAllow: true,
  },
  {
    id: "collaboratori",
    label: "Collaboratori",
    path: "/collaboratori",
    iconRegular: "person.2.png",
    iconActive: "person.2.fill.png",
    showInNav: true,
    showInMenu: true,
    showInPermissions: true,
  },
  {
    id: "modelli",
    label: "Modelli",
    path: "/modelli",
    iconRegular: "text.document.png",
    iconActive: "text.document.fill.png",
    showInNav: true,
    showInMenu: true,
    showInPermissions: true,
  },
  {
    id: "generatore-turni",
    label: "Generatore Turni",
    path: "/generatore-turni",
    iconRegular: "calendar.circle.png",
    iconActive: "calendar.circle.fill.png",
    showInNav: true,
    showInMenu: true,
    showInPermissions: true,
  },
  {
    id: "timbrature",
    label: "Timbrature",
    path: "/timbrature",
    iconRegular: "clock.badge.png",
    iconActive: "clock.badge.fill.png",
    showInNav: true,
    showInMenu: true,
    showInPermissions: true,
  },
  {
    id: "presenze",
    label: "Presenze",
    path: "/presenze",
    iconRegular: "list.bullet.clipboard.png",
    iconActive: "list.clipboard.fill.png",
    showInNav: true,
    showInMenu: true,
    showInPermissions: true,
  },
  {
    id: "profilo",
    label: "Profilo",
    path: "/profilo",
    iconRegular: null,
    iconActive: null,
    showInNav: true,
    showInMenu: true,
    showInPermissions: false,
    alwaysAllow: true,
  },
  {
    id: "permessi",
    label: "Permessi",
    path: "/permessi",
    iconRegular: null,
    iconActive: null,
    showInNav: true,
    showInMenu: true,
    showInPermissions: false,
    requiresBoss: true,
    navEmoji: "🔐",
  },
];
